export const COUNTRIES = [
  { code: "jp", name: "일본", flag: "🇯🇵" },
  { code: "cn", name: "중국", flag: "🇨🇳" },
  { code: "us", name: "미국", flag: "🇺🇸" },
  { code: "fr", name: "프랑스", flag: "🇫🇷" },
  { code: "it", name: "이탈리아", flag: "🇮🇹" },
  { code: "es", name: "스페인", flag: "🇪🇸" },
  { code: "de", name: "독일", flag: "🇩🇪" },
  { code: "gb", name: "영국", flag: "🇬🇧" },
  { code: "pt", name: "포르투갈", flag: "🇵🇹" },
  { code: "nl", name: "네덜란드", flag: "🇳🇱" },
  { code: "ch", name: "스위스", flag: "🇨🇭" },
  { code: "at", name: "오스트리아", flag: "🇦🇹" },
  { code: "gr", name: "그리스", flag: "🇬🇷" },
  { code: "cz", name: "체코", flag: "🇨🇿" },
  { code: "hu", name: "헝가리", flag: "🇭🇺" },
  { code: "pl", name: "폴란드", flag: "🇵🇱" },
  { code: "hr", name: "크로아티아", flag: "🇭🇷" },
  { code: "tr", name: "터키", flag: "🇹🇷" },
  { code: "th", name: "태국", flag: "🇹🇭" },
  { code: "vn", name: "베트남", flag: "🇻🇳" },
  { code: "sg", name: "싱가포르", flag: "🇸🇬" },
  { code: "my", name: "말레이시아", flag: "🇲🇾" },
  { code: "id", name: "인도네시아", flag: "🇮🇩" },
  { code: "ph", name: "필리핀", flag: "🇵🇭" },
  { code: "hk", name: "홍콩", flag: "🇭🇰" },
  { code: "tw", name: "대만", flag: "🇹🇼" },
  { code: "in", name: "인도", flag: "🇮🇳" },
  { code: "ae", name: "두바이(UAE)", flag: "🇦🇪" },
  { code: "au", name: "호주", flag: "🇦🇺" },
  { code: "nz", name: "뉴질랜드", flag: "🇳🇿" },
  { code: "ca", name: "캐나다", flag: "🇨🇦" },
  { code: "mx", name: "멕시코", flag: "🇲🇽" },
  { code: "br", name: "브라질", flag: "🇧🇷" },
  { code: "ar", name: "아르헨티나", flag: "🇦🇷" },
  { code: "za", name: "남아프리카", flag: "🇿🇦" },
  { code: "ma", name: "모로코", flag: "🇲🇦" },
  { code: "eg", name: "이집트", flag: "🇪🇬" },
  { code: "ru", name: "러시아", flag: "🇷🇺" },
  { code: "kr", name: "한국", flag: "🇰🇷" },
];

export function getCountry(code) {
  return COUNTRIES.find((c) => c.code === code) || null;
}
